#!/usr/bin/env node
'use strict';
/**
 * CulinaryVault static site generator.
 *
 *   node src/build.js
 *
 * Reads src/data/*, renders every page into the repository root, copies
 * assets and emits search-index.json, sitemap.xml, robots.txt, manifest.json
 * and feed.xml. No dependencies — Node 18+ only.
 *
 * Output goes to the root so the repository can be served as-is (GitHub Pages
 * from the repo root, or Netlify/Vercel with publish "."). That means the
 * output directory also contains the source, so the build NEVER wipes its
 * output directory wholesale — see cleanOutput() below.
 */

const fs = require('fs');
const path = require('path');

const { esc, clamp, slugify, plural, CATEGORIES, CUISINES, DIET_TAGS } = require('./lib/util');
const { plainList } = require('./lib/ingredients');
const { build: buildHubs } = require('./lib/ingredient-hubs');
const publishedReviews = require('./data/reviews.json');
const { derivedTags } = require('./lib/diet-derived');
const { expand: expandKeywords, forCategory: keywordsForCategory,
        forCuisine: keywordsForCuisine, forIngredient: keywordsForIngredient,
        searchTerms } = require('./lib/keywords');
const { SITE, slug } = require('./templates/layout');
const { recipeCount } = require('./data/stats');
const ads = require('./templates/ads');
const pages = require('./templates/pages');
const recipePage = require('./templates/recipe-page');

const ROOT = path.join(__dirname, '..');
const OUT = ROOT;               /* generated site is written to the repo root */
const SRC = __dirname;

/* Everything the build creates, and nothing else. cleanOutput() removes only
   these, because the output directory is also the project directory. */
const GENERATED_DIRS = ['assets', 'recipes', 'categories', 'cuisines', 'ingredients',
  'about', 'contact', 'search', 'favourites'];
const GENERATED_FILES = ['index.html', '404.html', 'sitemap.xml', 'robots.txt',
  'manifest.json', 'feed.xml', 'search-index.json', '_redirects'];

/* Never removable, whatever else changes. A typo in GENERATED_* that collided
   with one of these would otherwise delete the project. */
const PROTECTED = new Set(['.git', '.github', '.gitignore', '.nojekyll', 'src', 'tools',
  'node_modules', 'package.json', 'package-lock.json', 'README.md',
  'images-attribution.md', 'netlify.toml', 'vercel.json',
  /* A second, self-contained project shares this repository root. It builds
     itself and must never be touched by this build. */
  'travel-destinations']);

/* --------------------------------------------------------------- helpers */
function mkdir(dir) { fs.mkdirSync(dir, { recursive: true }); }

/**
 * Remove the previous build's output without touching anything else.
 *
 * The old implementation deleted the whole output directory. That was safe
 * when it was dist/; pointed at the repository root it would delete the
 * source, the tooling and .git, so it is deliberately replaced with a
 * targeted clean guarded by an explicit allow-list.
 */
function cleanOutput() {
  const names = [...GENERATED_DIRS, ...GENERATED_FILES];

  /* Validate the whole list before removing anything. Deleting as we validate
     would leave the site half-cleaned and unbuilt if a later entry failed. */
  const targets = names.map(name => {
    if (PROTECTED.has(name)) {
      throw new Error(`refusing to clean "${name}": it is a protected project path`);
    }
    if (name.includes('/') || name.includes('\\') || name === '.' || name === '..') {
      throw new Error(`refusing to clean unsafe path "${name}"`);
    }
    const target = path.join(OUT, name);
    if (!target.startsWith(OUT + path.sep)) {
      throw new Error(`refusing to clean outside the output directory: ${name}`);
    }
    return target;
  });

  for (const target of targets) fs.rmSync(target, { recursive: true, force: true });
}

function writePage(relPath, html) {
  const target = path.join(OUT, relPath);
  mkdir(path.dirname(target));
  fs.writeFileSync(target, html);
}

function copyDir(from, to) {
  mkdir(to);
  for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
    const src = path.join(from, entry.name);
    const dst = path.join(to, entry.name);
    if (entry.isDirectory()) copyDir(src, dst);
    else fs.copyFileSync(src, dst);
  }
}

/* ------------------------------------------------------------ load data */

/**
 * The image manifest carries values that templates interpolate directly into
 * `style` and `src` attributes (colour, LQIP data URI, filename). It is
 * generated by the Python pipeline from third-party API responses, so each
 * field is pattern-checked here rather than trusted — one gate protecting
 * every template.
 */
const HEX_COLOUR = /^#[0-9a-f]{6}$/i;
const LQIP_URI = /^data:image\/jpeg;base64,[A-Za-z0-9+/]+=*$/;
const FILE_SLUG = /^[a-z0-9-]+$/;

function validateImage(entry, slug) {
  const clean = {};
  for (const key of ['hero', 'process']) {
    const data = entry[key];
    if (!data) { clean[key] = null; continue; }
    if (!FILE_SLUG.test(data.file || '')) {
      throw new Error(`"${slug}": image ${key} has an unsafe filename: ${JSON.stringify(data.file)}`);
    }
    if (!HEX_COLOUR.test(data.color || '')) {
      throw new Error(`"${slug}": image ${key} has an invalid colour: ${JSON.stringify(data.color)}`);
    }
    if (data.lqip && !LQIP_URI.test(data.lqip)) {
      throw new Error(`"${slug}": image ${key} has a malformed LQIP data URI`);
    }
    clean[key] = data;
  }
  return clean;
}

function loadRecipes() {
  /* The catalogue is split across two volumes, each with its own details
     directory. They are merged here so the rest of the build only ever sees
     one flat list of recipes. */
  const catalog = [...require('./data/catalog'), ...require('./data/catalog-2'),
                   ...require('./data/catalog-3'), ...require('./data/catalog-4'),
                   ...require('./data/catalog-5')];
  const details = {};
  for (const dir of ['details', 'details2', 'details3', 'details4', 'details5']) {
    const detailsDir = path.join(SRC, 'data', dir);
    for (const file of fs.readdirSync(detailsDir).filter(f => f.endsWith('.js'))) {
      Object.assign(details, require(path.join(detailsDir, file)));
    }
  }

  /* A slug appearing in both volumes would silently overwrite one recipe's
     details with the other's, so it fails the build instead. */
  const seen = new Set();
  for (const row of catalog) {
    if (seen.has(row.slug)) throw new Error(`Duplicate recipe slug "${row.slug}" across catalogues`);
    seen.add(row.slug);
  }
  const images = JSON.parse(fs.readFileSync(path.join(SRC, 'data', 'images.json'), 'utf8'));

  /* Publication dates are derived deterministically so the build is
     reproducible: recipes are spread backwards from a fixed epoch, with
     anything flagged "new" pulled to the front. */
  const EPOCH = Date.UTC(2026, 6, 1);
  const DAY = 86400000;

  const recipes = catalog.map((row, index) => {
    const detail = details[row.slug];
    if (!detail) throw new Error(`Missing recipe detail for "${row.slug}"`);
    for (const field of ['d', 'meta', 'kw', 'why', 'ing', 'st', 'tips', 'pair', 'store', 'nut']) {
      if (!detail[field]) throw new Error(`"${row.slug}" is missing the "${field}" field`);
    }
    if (detail.nut.length !== 7) throw new Error(`"${row.slug}" nutrition needs 7 values`);

    const image = validateImage(images[row.slug] || {}, row.slug);
    const recency = row.badges.includes('new') ? index * 2 : 40 + index * 5;
    const published = EPOCH - recency * DAY;

    /* Derived tags join the hand-written ones. They are computed from the
       nutrition figures and ingredient list, so they cannot fall out of step
       with the recipe the way the typed ones did. */
    const tags = [...row.tags, ...derivedTags(detail).filter(tag => !row.tags.includes(tag))];

    const built = {
      ...row,
      tags,
      totalTime: row.prep + row.cook,
      description: detail.d,
      meta: clamp(detail.meta, 158),
      keywords: detail.kw,
      /* Optional, and absent on every recipe today. Both exist so the schema
         appears the moment a real asset does — see src/lib/media.js. */
      video: detail.video || null,
      publishedReviews: publishedReviews[row.slug] || [],
      why: detail.why,
      ingredients: detail.ing,
      steps: detail.st,
      tips: detail.tips,
      pairings: detail.pair,
      storage: detail.store,
      nutrition: detail.nut,
      cardBlurb: clamp(detail.d, 118),
      imageData: image.hero || null,
      processData: image.process || null,
      /* The cuisine is a proper noun and stays capitalised; the category is
         a common noun and reads better lower case. */
      imageAlt: `${row.title} — ${row.cuisine} ${row.category.toLowerCase()} recipe, served and ready to eat`,
      processAlt: `Ingredients and preparation for ${row.title.toLowerCase()}`,
      published,
      datePublished: new Date(published).toISOString().slice(0, 10),
      dateModified: new Date(EPOCH).toISOString().slice(0, 10),
      popularity: row.reviews * row.rating
    };

    /* Widen the four curated keywords into the long-tail phrases the row
       already supports. This runs after the object is assembled because it
       reads the ingredients and storage note as well as the catalogue row. */
    built.keywords = expandKeywords(built);
    return built;
  });

  /* Related recipes: same cuisine first, then same category, never itself. */
  const byPopularity = (a, b) => b.popularity - a.popularity;
  for (const recipe of recipes) {
    const sameCuisine = recipes.filter(r => r.slug !== recipe.slug && r.cuisine === recipe.cuisine).sort(byPopularity);
    const sameCategory = recipes.filter(r => r.slug !== recipe.slug && r.category === recipe.category).sort(byPopularity);
    const seen = new Set([recipe.slug]);
    const related = [];
    for (const candidate of sameCuisine.concat(sameCategory)) {
      if (seen.has(candidate.slug)) continue;
      seen.add(candidate.slug);
      related.push(candidate);
      if (related.length === 4) break;
    }
    recipe.related = related;
  }

  return recipes;
}

/* ------------------------------------------------------------- context */
function buildContext(recipes) {
  const criticalCss = fs.readFileSync(path.join(SRC, 'assets', 'css', 'critical.css'), 'utf8')
    .replace(/\/\*[\s\S]*?\*\//g, '')      // strip comments
    .replace(/\s+/g, ' ')                   // collapse whitespace
    .replace(/\s*([{}:;,>])\s*/g, '$1')
    .replace(/;}/g, '}')
    .trim();

  const count = (list, key) => list.reduce((acc, r) => {
    acc[r[key]] = (acc[r[key]] || 0) + 1;
    return acc;
  }, {});

  const categoryCounts = count(recipes, 'category');
  const cuisineCounts = count(recipes, 'cuisine');
  const topCuisines = Object.keys(cuisineCounts).sort((a, b) => cuisineCounts[b] - cuisineCounts[a] || a.localeCompare(b));

  const tagCounts = {};
  for (const tag of DIET_TAGS) tagCounts[tag] = recipes.filter(r => r.tags.includes(tag)).length;

  const timeCounts = {};
  for (const t of [15, 30, 45, 60, 120]) timeCounts[t] = recipes.filter(r => r.totalTime <= t).length;

  return {
    recipes,
    criticalCss,
    categoryCounts,
    cuisineCounts,
    topCuisines,
    facets: {
      category: categoryCounts,
      cuisine: cuisineCounts,
      cuisineList: topCuisines,
      tag: tagCounts,
      difficulty: count(recipes, 'difficulty'),
      time: timeCounts
    }
  };
}

/* -------------------------------------------------------- search index */
function searchIndex(recipes) {
  return recipes.map(r => ({
    g: r.slug,                                   // slug
    t: r.title,                                  // title
    c: r.cuisine,                                // cuisine
    n: r.category,                               // category
    f: r.tags,                                   // dietary flags
    d: r.difficulty,
    m: r.totalTime,
    p: r.prep,
    o: r.cook,
    v: r.servings,
    r: r.rating,
    w: r.popularity,
    z: r.published,
    e: r.cardBlurb,
    a: r.imageAlt,
    i: r.imageData ? r.imageData.file : null,
    k: r.imageData ? r.imageData.color : null,
    /* Pre-lowered searchable blob: title, cuisine, category, tags,
       keywords and every ingredient name. */
    s: [
      r.title, r.cuisine, r.category, r.difficulty,
      r.tags.join(' '), searchTerms(r.title, r.keywords).join(' '),
      plainList(r.ingredients).join(' ')
    ].join(' ').toLowerCase()
  }));
}

/* --------------------------------------------------------- site plumbing */
function sitemap(recipes, ctx) {
  const today = new Date().toISOString().slice(0, 10);
  const entry = (loc, lastmod, changefreq, priority) =>
    `  <url>\n    <loc>${SITE.origin}${SITE.base}${loc}</loc>\n` +
    `    <lastmod>${lastmod}</lastmod>\n` +
    `    <changefreq>${changefreq}</changefreq>\n` +
    `    <priority>${priority}</priority>\n  </url>`;

  const urls = [
    entry('', today, 'daily', '1.0'),
    entry('recipes/', today, 'daily', '0.9'),
    entry('categories/', today, 'weekly', '0.8'),
    entry('cuisines/', today, 'weekly', '0.8'),
    entry('ingredients/', today, 'weekly', '0.8'),
    entry('search/', today, 'monthly', '0.4'),
    /* /favourites/ is noindex — device-local content, nothing to crawl. */
    entry('about/', today, 'monthly', '0.5'),
    entry('contact/', today, 'monthly', '0.4')
  ];

  for (const name of Object.keys(CATEGORIES)) {
    urls.push(entry(`categories/${slug(name)}/`, today, 'weekly', '0.7'));
  }
  for (const name of ctx.topCuisines) {
    urls.push(entry(`cuisines/${slug(name)}/`, today, 'weekly', '0.7'));
  }
  for (const hub of ctx.hubs || []) {
    urls.push(entry(`ingredients/${hub.slug}/`, today, 'weekly', '0.7'));
  }
  for (const recipe of recipes) {
    const image = recipe.imageData
      ? `\n    <image:image>\n      <image:loc>${SITE.origin}${SITE.base}assets/img/recipes/${recipe.imageData.file}.jpg</image:loc>\n` +
        `      <image:title>${esc(recipe.title)}</image:title>\n` +
        `      <image:caption>${esc(recipe.imageAlt)}</image:caption>\n    </image:image>`
      : '';
    urls.push(
      `  <url>\n    <loc>${SITE.origin}${SITE.base}recipes/${recipe.slug}/</loc>\n` +
      `    <lastmod>${recipe.dateModified}</lastmod>\n` +
      `    <changefreq>monthly</changefreq>\n` +
      `    <priority>${recipe.badges.includes('editors') ? '0.9' : '0.8'}</priority>${image}\n  </url>`
    );
  }

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
${urls.join('\n')}
</urlset>\n`;
}

function robots() {
  return `# CulinaryVault — ${SITE.origin}${SITE.base}
User-agent: *
Allow: /

# Filtered directory views duplicate the canonical listing
Disallow: /*?q=
Disallow: /*?sort=
Disallow: /*?tag=
Disallow: /*?time=
Disallow: /*?cuisine=
Disallow: /*?category=
Disallow: /*?difficulty=

# Personal, device-local pages have nothing to index
Disallow: /favourites/

# The site is generated into the repository root, so the project's own
# directories sit alongside it. Nothing there is worth crawling.
Disallow: /src/
Disallow: /tools/

User-agent: Googlebot
Allow: /
Allow: /assets/img/

User-agent: Googlebot-Image
Allow: /assets/img/

# Be polite to smaller crawlers
User-agent: AhrefsBot
Crawl-delay: 10

User-agent: SemrushBot
Crawl-delay: 10

Sitemap: ${SITE.origin}${SITE.base}sitemap.xml
`;
}

function manifest() {
  return JSON.stringify({
    name: `CulinaryVault — ${recipeCount} World Recipes`,
    short_name: 'CulinaryVault',
    description: SITE.tagline,
    start_url: SITE.base,
    scope: SITE.base,
    display: 'standalone',
    orientation: 'portrait-primary',
    background_color: '#fbf7f0',
    theme_color: '#b8492c',
    lang: 'en-GB',
    dir: 'ltr',
    categories: ['food', 'lifestyle', 'books'],
    icons: [
      { src: `${SITE.base}assets/img/icon-192.png`, sizes: '192x192', type: 'image/png', purpose: 'any' },
      { src: `${SITE.base}assets/img/icon-512.png`, sizes: '512x512', type: 'image/png', purpose: 'any' },
      { src: `${SITE.base}assets/img/icon-512.png`, sizes: '512x512', type: 'image/png', purpose: 'maskable' }
    ],
    shortcuts: [
      { name: 'All recipes', url: `${SITE.base}recipes/` },
      { name: 'Saved recipes', url: `${SITE.base}favourites/` },
      { name: 'Search', url: `${SITE.base}search/` }
    ]
  }, null, 2);
}

function feed(recipes) {
  const latest = recipes.slice().sort((a, b) => b.published - a.published).slice(0, 25);
  const items = latest.map(r => `    <item>
      <title>${esc(r.title)}</title>
      <link>${SITE.origin}${SITE.base}recipes/${r.slug}/</link>
      <guid isPermaLink="true">${SITE.origin}${SITE.base}recipes/${r.slug}/</guid>
      <pubDate>${new Date(r.published).toUTCString()}</pubDate>
      <category>${esc(r.category)}</category>
      <description>${esc(r.meta)}</description>
    </item>`).join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>${esc(SITE.name)}</title>
    <link>${SITE.origin}${SITE.base}</link>
    <description>${esc(SITE.tagline)}</description>
    <language>en-gb</language>
    <lastBuildDate>${new Date().toUTCString()}</lastBuildDate>
    <atom:link href="${SITE.origin}${SITE.base}feed.xml" rel="self" type="application/rss+xml"/>
${items}
  </channel>
</rss>\n`;
}

/* ------------------------------------------------------------------ main */
function build() {
  const started = Date.now();
  const recipes = loadRecipes();
  const ctx = buildContext(recipes);

  cleanOutput();
  mkdir(OUT);

  /* Static assets ------------------------------------------------------ */
  copyDir(path.join(SRC, 'assets'), path.join(OUT, 'assets'));

  /* Pages -------------------------------------------------------------- */
  writePage('index.html', pages.home(ctx));

  writePage('recipes/index.html', pages.directory(ctx, {
    mode: 'all',
    title: 'All Recipes',
    heading: `All ${recipes.length} recipes`,
    eyebrow: 'The full directory',
    intro: 'Every recipe in the Vault, filterable by category, cuisine, dietary need, difficulty and total time. Sorted by what readers cook most.',
    description: `Browse all ${recipes.length} tested recipes on CulinaryVault. Filter by cuisine, category, dietary needs, difficulty and cooking time.`,
    keywords: ['all recipes', 'recipe directory', 'browse recipes', 'recipe filter',
               'recipe index', 'full recipe list', 'browse by cuisine', 'browse by category',
               'filter recipes by diet', 'vegetarian recipes', 'vegan recipes',
               'gluten free recipes', 'quick recipes', 'easy recipes', 'dinner ideas',
               'what to cook tonight', 'tested recipes', 'recipes with photos',
               'sort recipes by rating', 'find a recipe'],
    path: 'recipes/',
    trail: [{ name: 'Recipes' }],
    seed: recipes.slice().sort((a, b) => b.popularity - a.popularity).slice(0, 24)
  }));

  writePage('search/index.html', pages.directory(ctx, {
    mode: 'search',
    title: 'Search Recipes',
    heading: 'Search the Vault',
    eyebrow: 'Find a recipe',
    intro: 'Search by dish, ingredient, cuisine or technique. Results update as you type and can be narrowed with the filters.',
    description: `Search ${recipes.length} tested recipes by dish, ingredient, cuisine or technique. Instant results with filters for time, difficulty and diet.`,
    keywords: ['recipe search', 'find recipes by ingredient', 'search recipes',
               'search by ingredient', 'what can i cook with', 'recipe finder',
               'ingredient search', 'leftover ingredient recipes', 'cook with what i have',
               'find recipes by name', 'search recipes by cuisine', 'recipe lookup'],
    path: 'search/',
    active: 'search',
    index: false,
    trail: [{ name: 'Search' }]
  }));

  writePage('favourites/index.html', pages.directory(ctx, {
    mode: 'favourites',
    title: 'Saved Recipes',
    heading: 'Your saved recipes',
    eyebrow: 'Favourites',
    intro: 'Everything you have hearted, stored in this browser only. No account, no sync, no tracking.',
    description: 'Your saved CulinaryVault recipes, stored locally in your browser.',
    path: 'favourites/',
    active: 'favourites',
    noindex: true,
    index: false,
    trail: [{ name: 'Saved recipes' }]
  }));

  writePage('categories/index.html', pages.categoriesIndex(ctx));
  /* Ingredient hubs ---------------------------------------------------- */
  /* Built here rather than in buildContext so the failure is loud: a hub whose
     contents contradict a recipe's own diet tag is a data bug, and shipping the
     page would put a vegan dish under Chicken. */
  const { hubs, conflicts } = buildHubs(recipes);
  if (conflicts.length) {
    throw new Error(`Ingredient hub conflicts:\n  ${conflicts.join('\n  ')}`);
  }
  ctx.hubs = hubs;
  writePage('ingredients/index.html', pages.ingredientsIndex(ctx));
  for (const hub of hubs) {
    writePage(`ingredients/${hub.slug}/index.html`, pages.taxonomyPage(ctx, {
      recipes: hub.recipes,
      title: `${hub.name} Recipes`,
      heading: `${hub.name} recipes`,
      eyebrow: 'Ingredient',
      intro: `${hub.blurb} ${plural(hub.recipes.length, 'recipe')} on the site call for ${hub.name.toLowerCase()}.`,
      description: clamp(`${plural(hub.recipes.length, hub.name.toLowerCase() + ' recipe')} on CulinaryVault. ${hub.blurb}`, 158),
      keywords: keywordsForIngredient(hub),
      path: `ingredients/${hub.slug}/`,
      active: 'ingredients',
      newsId: `ing-${hub.slug}-news`,
      trail: [{ name: 'Ingredients', url: `${SITE.base}ingredients/` }, { name: hub.name }]
    }));
  }

  writePage('cuisines/index.html', pages.cuisinesIndex(ctx));
  writePage('about/index.html', pages.about(ctx));
  writePage('contact/index.html', pages.contact(ctx));
  writePage('404.html', pages.notFound(ctx));

  /* Category landing pages --------------------------------------------- */
  for (const name of Object.keys(CATEGORIES)) {
    const list = recipes.filter(r => r.category === name).sort((a, b) => b.popularity - a.popularity);
    writePage(`categories/${slug(name)}/index.html`, pages.taxonomyPage(ctx, {
      recipes: list,
      title: `${name} Recipes`,
      heading: `${name} recipes`,
      eyebrow: 'Category',
      intro: `${CATEGORIES[name]} ${plural(list.length, 'tested recipe')}, ranked by what readers cook most.`,
      description: clamp(`${name} recipes from CulinaryVault: ${plural(list.length, 'tested dish', 'tested dishes')}. ${CATEGORIES[name]}`, 158),
      keywords: keywordsForCategory(name, list),
      path: `categories/${slug(name)}/`,
      active: 'categories',
      newsId: `cat-${slug(name)}-news`,
      trail: [{ name: 'Categories', url: `${SITE.base}categories/` }, { name }]
    }));
  }

  /* Cuisine landing pages ---------------------------------------------- */
  for (const name of ctx.topCuisines) {
    const list = recipes.filter(r => r.cuisine === name).sort((a, b) => b.popularity - a.popularity);
    const meta = CUISINES[name] || { flag: '', blurb: '' };
    writePage(`cuisines/${slug(name)}/index.html`, pages.taxonomyPage(ctx, {
      recipes: list,
      title: `${name} Recipes`,
      heading: `${name} recipes`,
      eyebrow: `${meta.flag} Cuisine`,
      intro: `${meta.blurb} ${plural(list.length, 'tested ' + name + ' recipe')}, from the everyday to the ambitious.`,
      description: clamp(`${plural(list.length, 'tested ' + name + ' recipe')} on CulinaryVault. ${meta.blurb}`, 158),
      keywords: keywordsForCuisine(name, list),
      path: `cuisines/${slug(name)}/`,
      active: 'cuisines',
      newsId: `cui-${slug(name)}-news`,
      trail: [{ name: 'Cuisines', url: `${SITE.base}cuisines/` }, { name }]
    }));
  }

  /* Recipe pages -------------------------------------------------------- */
  for (const recipe of recipes) {
    writePage(`recipes/${recipe.slug}/index.html`, recipePage.render(recipe, ctx));
  }

  /* Data + plumbing ----------------------------------------------------- */
  fs.writeFileSync(path.join(OUT, 'search-index.json'), JSON.stringify(searchIndex(recipes)));
  fs.writeFileSync(path.join(OUT, 'sitemap.xml'), sitemap(recipes, ctx));
  fs.writeFileSync(path.join(OUT, 'robots.txt'), robots());
  fs.writeFileSync(path.join(OUT, 'manifest.json'), manifest());
  fs.writeFileSync(path.join(OUT, 'feed.xml'), feed(recipes));
  fs.writeFileSync(path.join(OUT, '_redirects'), '/*  /404.html  404\n');

  /* The one-slot document that repeat native banner placements are framed
     from. Written only when there is a unit to put in it. */
  const frameHtml = ads.frameDocument(SITE.base);
  if (frameHtml) {
    const framePath = path.join(OUT, ads.FRAME_PATH);
    fs.mkdirSync(path.dirname(framePath), { recursive: true });
    fs.writeFileSync(framePath, frameHtml);
  }

  /* Report --------------------------------------------------------------- */
  /* Walk only what we generated: at the repo root the tree also contains
     src/, tools/ and node_modules/. */
  const files = [];
  (function walk(dir) {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) walk(full);
      else files.push(full);
    }
  });
  for (const name of GENERATED_FILES) {
    const f = path.join(OUT, name);
    if (fs.existsSync(f)) files.push(f);
  }
  for (const name of GENERATED_DIRS) {
    const dir = path.join(OUT, name);
    if (!fs.existsSync(dir)) continue;
    (function collect(d) {
      for (const entry of fs.readdirSync(d, { withFileTypes: true })) {
        const full = path.join(d, entry.name);
        if (entry.isDirectory()) collect(full);
        else files.push(full);
      }
    })(dir);
  }

  const html = files.filter(f => f.endsWith('.html'));
  const bytes = files.reduce((total, f) => total + fs.statSync(f).size, 0);
  const withImages = recipes.filter(r => r.imageData).length;

  console.log(`CulinaryVault build complete in ${Date.now() - started}ms`);
  console.log(`  recipes      ${recipes.length} (${withImages} with photography, ${recipes.length - withImages} using gradient placeholders)`);
  console.log(`  html pages   ${html.length}`);
  console.log(`  total files  ${files.length}`);
  console.log(`  output size  ${(bytes / 1024 / 1024).toFixed(1)} MB`);
  console.log(`  origin       ${SITE.origin}${SITE.base}`);
}

if (require.main === module) {
  try {
    build();
  } catch (error) {
    console.error('Build failed:', error.message);
    process.exit(1);
  }
}

module.exports = { build, loadRecipes, buildContext, searchIndex };
